root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
  bin = "./scripts/start.sh"
  # Creates the debugger build from grafana-server that listens on 3222
  # cmd = "mage -v debugger"
  # Above command doesn't work because ptrace doesn't work on WSL2?
  cmd = "mage -v build:debug"
  delay = 1000
  exclude_dir = ["node_modules", "src"]
  exclude_file = []
  exclude_unchanged = false
  follow_symlink = false
  full_bin = ""
  include_dir = ["pkg"]
  include_ext = ["go"]
  kill_delay = "0s"
  log = "build-errors.log"
  send_interrupt = false
  stop_on_error = true

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  time = false

[misc]
  clean_on_exit = false

[screen]
  clear_on_rebuild = false
