# This GitHub Action automates the process of building Grafana plugins.
# (For more information, see https://github.com/grafana/plugin-actions/blob/main/build-plugin/README.md)
name: Release

on:
  push:
    tags:
      - 'v*' # Run workflow on version tags, e.g. v1.0.0.

permissions: read-all

jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: 'jck/add-version'
      # Extract the tag name
      - name: Extract tag name
        id: extract_tag
        run: |
          TAG_NAME=${GITHUB_REF#refs/tags/}
          echo "TAG_NAME=$TAG_NAME" >> $GITHUB_ENV

      - name: Print tag name
        run: echo "The current version is $TAG_NAME"
      
      # Update version.json with the tag name
      - name: Update version.json
        run: |
          jq --arg version "$TAG_NAME" '.version = $version' $GITHUB_WORKSPACE/src/version.json > tmp.json && mv tmp.json $GITHUB_WORKSPACE/src/version.json
    
      - uses: grafana/plugin-actions/build-plugin@release
        # Uncomment to enable plugin signing
        # (For more info on how to generate the access policy token see https://grafana.com/developers/plugin-tools/publish-a-plugin/sign-a-plugin#generate-an-access-policy-token)
        #with:
        # Make sure to save the token in your repository secrets
        #policy_token: $
        # Usage of GRAFANA_API_KEY is deprecated, prefer `policy_token` option above
        #grafana_token: $
